"""add notifications and threads

Revision ID: 166d7c5261d2
Revises: 0b80bece37b9
Create Date: 2026-05-09 11:10:16.059518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166d7c5261d2'
down_revision: Union[str, Sequence[str], None] = '0b80bece37b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('type', sa.Enum('ADMIN_BROADCAST', 'ADMIN_MESSAGE', 'LISTING_EXPIRING_SOON', 'LISTING_EXPIRED', 'LISTING_REMOVED', 'LISTING_PHONE_REVEALED', 'WELCOME', 'ACCOUNT_WARNING', 'ACCOUNT_SUSPENDED', 'ACCOUNT_REINSTATED', 'SAVED_PRICE_DROP', 'SAVED_LISTING_SOLD', 'SAVED_LISTING_REMOVED', 'RATING_RECEIVED', name='notificationtype'), nullable=False),
    sa.Column('is_noreply', sa.Boolean(), nullable=False),
    sa.Column('user_has_unread', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_threads_user_id'), 'notification_threads', ['user_id'], unique=False)
    op.create_table('notification_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sender_is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['notification_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_messages_thread_id'), 'notification_messages', ['thread_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('ADMIN_BROADCAST', 'ADMIN_MESSAGE', 'LISTING_EXPIRING_SOON', 'LISTING_EXPIRED', 'LISTING_REMOVED', 'LISTING_PHONE_REVEALED', 'WELCOME', 'ACCOUNT_WARNING', 'ACCOUNT_SUSPENDED', 'ACCOUNT_REINSTATED', 'SAVED_PRICE_DROP', 'SAVED_LISTING_SOLD', 'SAVED_LISTING_REMOVED', 'RATING_RECEIVED', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_messages_thread_id'), table_name='notification_messages')
    op.drop_table('notification_messages')
    op.drop_index(op.f('ix_notification_threads_user_id'), table_name='notification_threads')
    op.drop_table('notification_threads')
    # ### end Alembic commands ###
